### ISSUE TITLE
Organize All App Logic Inside the src Directory

### ISSUE THREAD

**Issue by hasnainAli22** [umairmanzoor1143/boiler-plate-react-native#1]
### Description  
Currently, the project structure does not enforce a clear separation of concerns, leading to a messy and hard-to-maintain codebase as the application scales. To improve project organization and maintainability, I propose that all app-related logic, including components, screens, utilities, styles, and other core functionalities, be moved inside a dedicated `src` directory.  

#### Benefits  
1. **Improved Organization**: Keeping all app logic under `src` creates a clear boundary between app code and configuration files (e.g., `package.json`, `README.md`).
2. **Easier Navigation**: Developers can quickly locate application-specific files without sifting through unrelated project-level files.
3. **Scalability**: As the app grows, having a consistent structure makes it easier to manage and onboard new developers.
4. **Industry Standards**: Aligns with best practices seen in modern React Native projects.  

#### Suggested Structure  
```plaintext
project/
├── src/
│   ├── components/
│   ├── screens/
│   ├── utils/
│   ├── navigation/
│   └── styles/
├── node_modules/
├── package.json
└── other-config-files
```

This structure ensures that all app-specific logic resides in a single, manageable directory (src), promoting consistency and clarity.

**Comment by umairmanzoor1143** [comment]
This structure ensures that all app-specific logic resides in a single, manageable directory (src), promoting consistency and clarity.
